version: '2'
syncs:
  # name of mount
  tourney_app-sync:
    src: '.'
    sync_strategy: unison
    sync_excludes:
      - .git
      - node_modules
      - client
      - build
      - /coverage
      - npm-debug.log
      - .env
      - .vscode
      - .dbData
      - .sessionsData
      - .circleci
options:
  compose-file-path: 'docker/dev/docker-compose.yml'
  verbose: true
